# Minimal Netlify configuration

[build]
  # Use our reliable static build script until we can resolve the Vite build issues
  command = "bash static-build.sh"
  publish = "dist"
  
# Basic environment settings
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
