# Minimal Netlify configuration

[build]
  # Use our custom node script for more reliable builds
  command = "node netlify-build.js"
  publish = "dist"
  
# Basic environment settings
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
