# Minimal Netlify configuration

[build]
  # Use our simple shell script for the most reliable builds
  command = "bash netlify-build.sh"
  publish = "dist"
  
# Basic environment settings
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
