# Standard Netlify configuration for React/Vite app

[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "production"

# SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache settings for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
