# Minimal Netlify configuration

[build]
  # Use our improved build script that attempts to build the React app with fallback
  command = "bash netlify-build-react.sh"
  publish = "dist"
  
# Basic environment settings
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
